Clean code exercise
Rovisible/onboarding-main pull request #1
Opened 2023-08-30 19:35 UTC by Rovisible

Changes to Program.cs in ToDo project aimed to refactor file applying clean code principles.

2023-08-31 01:44 UTC, TC-jBautista requested changes
Leave some comments

2023-08-31 01:44 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
> +            } while (selectedOption != 4);
Having magic numbers (an embedded numerical constant that appears without explanation) is not a good idea. Consider using an enum to improve the readability of your code

2023-08-31 01:44 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
> +        public static List<string> Tasks { get; set; }
Here you can use the C# auto-initialize property feature
```suggestion
        public static List<string> Tasks = new List<string>();
```

2023-08-31 01:44 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
> +            return Convert.ToInt32(Console.ReadLine());
In some cases, it is better to have more lines to have a more readable code. I suggest keeping these 2 instructions in 2 lines. Also, would be fine if you validate the correct input according to the menu options you have.
```suggestion
            string menuSelected = Console.ReadLine();
            return Convert.ToInt32(menuSelected);
```

2023-08-31 01:44 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
> +            string task = Console.ReadLine();
`taskName` would be a more descriptive name, what do you think?

2023-08-31 01:44 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
> +                if (Tasks.Count > 0)
Here you have a nested `if`, so, you can combine the second if with the first one in order to follow the principle KISS (Keep It Short and Simple). Also, you should add extra validation to avoid exceptions, for example, if the user enters a number bigger than the number of elements in the TaskList, an `Index Out Of Range` exception will be raised

2023-08-31 01:44 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
> -            catch (Exception)
Why did you remove the `try-catch` statement?

2023-08-31 01:44 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
> +            if (Tasks == null || Tasks.Count == 0)
Please follow the KISS principle and refactor this logic
```suggestion
            if (TaskList?.Count > 0)
              // logic to show the task list
            else
              // logic when there are no tasks
```

2023-08-31 01:44 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
> +                    Console.WriteLine("Task " + task + " deleted");
You should use string interpolation for a better coding style
```suggestion
                    Console.WriteLine($"Task {task} deleted");
```

2023-08-31 01:44 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
>              }
Instead of using a `for` loop, you can use the `foreach` statement, it's more natural for reading and we will be following the KISS principle. Also, you should use string interpolation to have better logic to build the message. What do you think about refactoring this logic like this:
```suggestion
            var indexTask = 1;
            TaskList.ForEach(task => Console.WriteLine($"{indexTask++}. {task}"));```

2023-08-31 16:45 UTC, Rovisible commented on csharp/Clean Code/ToDo/Program.cs
> +        public static List<string> Tasks { get; set; }
Can you please clarify a little bit further? Is this suggestion based in the fact that the list is initialized immediately at the start of the main and that is why the lazy initialization is worthless in this specific case? Or should I always prioritize to initialize the objects at class definition to ensure they are not null if something were to read them first?

I am also curious to know if initializing the property like this:
```suggestion
        public static List<string> Tasks { get; set; } = new List<string>();
```
would be against syntax conventions/practices (I like how it looks :D)

2023-08-31 23:26 UTC, Rovisible commented on csharp/Clean Code/ToDo/Program.cs
> -            catch (Exception)
So that I could see the reason of any future failure and fix it instead of the catch block just ignoring it.

2023-09-04 20:34 UTC, merged

2023-09-12 17:53 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
> +        public static List<string> Tasks { get; set; }
@Rovisible in a previous C# version, to initialize a variable you must use the Constructor method. Now we can initialize a variable when we define it, so, this is useful to avoid initialize issues. The `{ get; set; }` code will work but a cleaner implementation could be just have `public static List<string> Tasks = new List<string>();`.

2023-09-12 17:54 UTC, TC-jBautista commented on csharp/Clean Code/ToDo/Program.cs
> -            catch (Exception)
Ok, got it